# Introduction to PyTorch

In [1]:
import torch

In [3]:
def activation(x):
    
    return 1/( 1+ torch.exp(-x))

In [21]:
## Generate some data
torch.manual_seed(7)


features = torch.rand(1,5)
#rand_like takes tensor and creates a tensor in the shape of feeded tensor
weights = torch.rand_like(features) 
bias = torch.randn(1,1)


In [33]:
output = activation(torch.mm(features, weights.T) + bias)
output

tensor([[0.8274]])

# Multilayer

In [34]:
torch.manual_seed(7)
features = torch.randn(1,3)


#Define the size opf each layer in our network
n_input = features.shape[1]

n_hidden = 2

n_output = 1

W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

# bias term for hdden and output layers
B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

In [51]:
hidden_output = activation(torch.mm(features, W1) + B1)
hidden_output

tensor([[0.6813, 0.4355]])

In [53]:
output = activation(torch.mm(hidden_output, W2) + B2)
output

tensor([[0.3171]])

# NumPy to Torch and back

In [54]:
import numpy as np

In [56]:
a = np.random.rand(4,3)
a

array([[0.57763641, 0.01598294, 0.76419364],
       [0.12111929, 0.32225178, 0.68324287],
       [0.36627252, 0.16347391, 0.03252465],
       [0.23015971, 0.48494835, 0.16827028]])

In [57]:
b = torch.from_numpy(a)
b

tensor([[0.5776, 0.0160, 0.7642],
        [0.1211, 0.3223, 0.6832],
        [0.3663, 0.1635, 0.0325],
        [0.2302, 0.4849, 0.1683]], dtype=torch.float64)

In [58]:
b.numpy()

array([[0.57763641, 0.01598294, 0.76419364],
       [0.12111929, 0.32225178, 0.68324287],
       [0.36627252, 0.16347391, 0.03252465],
       [0.23015971, 0.48494835, 0.16827028]])

Remember the memory is shared between the Numpy array and Torch.
If you do any in-place operation on either object, it will change the other as well

In [60]:
#In-place multiplication
b.mul_(2)

tensor([[2.3105, 0.0639, 3.0568],
        [0.4845, 1.2890, 2.7330],
        [1.4651, 0.6539, 0.1301],
        [0.9206, 1.9398, 0.6731]], dtype=torch.float64)

In [62]:
b

tensor([[2.3105, 0.0639, 3.0568],
        [0.4845, 1.2890, 2.7330],
        [1.4651, 0.6539, 0.1301],
        [0.9206, 1.9398, 0.6731]], dtype=torch.float64)