# Building Neural Network using NN module



<img src="mlp_mnist.png" width=600px>

> **Exercise:** Create a network with 784 input units, a hidden layer with 128 units and a ReLU activation, then a hidden layer with 64 units and a ReLU activation, and finally an output layer with a softmax activation as shown above. You can use a ReLU activation with the `nn.ReLU` module or `F.relu` function.

In [28]:
### Run this cell
import torch.nn.functional as F
from torch import nn
import torch

from torchvision import datasets, transforms

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5,), (0.5,)),
                              ])
# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

In [68]:

class Network(nn.Module):
    
    def __init__(self):
        super().__init__()

        self.hidden1 = nn.Linear(784, 128)

        self.hidden2 = nn.Linear(128, 64)

        self.output = nn.Linear(64,10)
    
    def forward(self, X):
        
        X = self.hidden1(X)
        X = F.relu(X)
        X = self.hidden2(X)
        X = F.relu(X)
        X = self.output(X)
        X = F.softmax(X)

        return X
    

In [69]:
model = Network()

model

Network(
  (hidden1): Linear(in_features=784, out_features=128, bias=True)
  (hidden2): Linear(in_features=128, out_features=64, bias=True)
  (output): Linear(in_features=64, out_features=10, bias=True)
)

In [70]:
print(model.hidden1.weight)
print(model.hidden2.weight)

Parameter containing:
tensor([[-0.0265, -0.0175, -0.0278,  ..., -0.0353,  0.0298,  0.0125],
        [ 0.0256,  0.0022,  0.0178,  ..., -0.0098, -0.0182, -0.0274],
        [ 0.0265,  0.0114,  0.0185,  ...,  0.0249, -0.0201, -0.0006],
        ...,
        [-0.0324,  0.0003,  0.0139,  ..., -0.0322,  0.0152, -0.0293],
        [-0.0139,  0.0123, -0.0198,  ...,  0.0335, -0.0325, -0.0240],
        [ 0.0130, -0.0283, -0.0228,  ..., -0.0283,  0.0350, -0.0227]],
       requires_grad=True)
Parameter containing:
tensor([[ 0.0356,  0.0216, -0.0579,  ..., -0.0698,  0.0803, -0.0539],
        [ 0.0516, -0.0146, -0.0704,  ...,  0.0606, -0.0253,  0.0314],
        [-0.0679,  0.0028,  0.0259,  ...,  0.0125,  0.0351, -0.0295],
        ...,
        [ 0.0589,  0.0637,  0.0110,  ...,  0.0453, -0.0356,  0.0284],
        [-0.0780,  0.0129,  0.0036,  ...,  0.0648, -0.0443,  0.0215],
        [ 0.0872, -0.0481, -0.0208,  ...,  0.0482, -0.0794, -0.0365]],
       requires_grad=True)


In [71]:
#Setting biases to all zeros
model.hidden1.bias.data.fill_(0)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])

# Forward Pass

In [84]:
# Get some data
dataiter = iter(trainloader)
images, label = dataiter.next()